### ISSUE TITLE
Просмотр тикета

### ISSUE THREAD

**Issue by Dmitry-407** [Club-Helper/frontend#16]
Такет, который должен содержать:

1. [x] Информацию об авторе тикета и времени отправки
2. [x] Статус тикета
3. [x] Историю действий с тикетом
4. [x] Возможность управлять статусом тикетом
5. [x] При первом подключении к тикету предложить отправить приветственное сообщение

**Comment by n1rwana** [comment]
api отправки приветственного сообщения.
