### ISSUE TITLE
Фильтрация все/мои

### ISSUE THREAD

**Issue by Dmitry-407** [Club-Helper/frontend#27]
Список шаблонов комментариев должен поддерживать фильтрацию по принципу все или только мои.

**Comment by n1rwana** [comment]
интерфейс сделан, жду api.

**Comment by Dmitry-407** [comment]
API уже поддерживает фильтрацию.

**Comment by Dmitry-407** [comment]
Закрывай issue когда изменения связанные с ними отправлены в мастер.
