### ISSUE TITLE
Возможность описаться от рассылки для пользователя

### ISSUE THREAD

**Issue by Dmitry-407** [Club-Helper/frontend#37]
😉 **Функционал для пользователя**

Пользователь должен видеть список рассылок и иметь возможность от неё отписаться. Это действие будет обратимо через службу поддержки.

**Comment by n1rwana** [comment]
жду api.

**Comment by Dmitry-407** [comment]
`mailings.cancellation`

**Comment by Dmitry-407** [comment]
`mailings.cancellation`
